{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kuiklySqlite/1.0.0/kuiklySqlite-1.0.0.module",
    "group": "net.shantu.kuiklysqlite",
    "module": "kuiklySqlite",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21-KBA-010"
          }
        }
      ],
      "files": [
        {
          "name": "kuiklySqlite-release.aar",
          "url": "kuiklySqlite-android-1.0.0.aar",
          "size": 2418103,
          "sha512": "0a1719550229f79dfab857adce2de9273d166a888820e601a5e3d21cc65602dc2a13e9a17b7f3deb53e545dbc82e562aabc67e8ba00fdb5bcf9b3f6306a84d94",
          "sha256": "3e57de82c3988bf3dc93c8ff904cc56c91556eccef543d6e3fdfaa3133a70c35",
          "sha1": "4a7f72542cb6bd820b8a45206b73494a5ac377cd",
          "md5": "d371f14d1145685178f59e6d30e99492"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.18.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21-KBA-010"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kuiklySqlite-release.aar",
          "url": "kuiklySqlite-android-1.0.0.aar",
          "size": 2418103,
          "sha512": "0a1719550229f79dfab857adce2de9273d166a888820e601a5e3d21cc65602dc2a13e9a17b7f3deb53e545dbc82e562aabc67e8ba00fdb5bcf9b3f6306a84d94",
          "sha256": "3e57de82c3988bf3dc93c8ff904cc56c91556eccef543d6e3fdfaa3133a70c35",
          "sha1": "4a7f72542cb6bd820b8a45206b73494a5ac377cd",
          "md5": "d371f14d1145685178f59e6d30e99492"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kuiklySqlite-android-1.0.0-sources.jar",
          "url": "kuiklySqlite-android-1.0.0-sources.jar",
          "size": 20620,
          "sha512": "02433a610f6c97f41307896fe00f2b0aa0cb82960e353b517083b66462a07519acdafd9d34eb3d4e738900d86d7315e4983a7a16a3ab40c0284d15df26e03828",
          "sha256": "1d61af9031cda7e1bd07f57df9a6cf59350398479f2a15b1b3a8afbbe55e5c8c",
          "sha1": "71cf66a266d05b72efa276eb0d6efd9b039554e1",
          "md5": "42a7839b2aa9d227fbe997bc90078466"
        }
      ]
    }
  ]
}
