{
  "formatVersion": "1.1",
  "component": {
    "group": "net.shantu.kuiklysqlite",
    "module": "kuiklySqlite-compiler",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "kuiklySqlite-compiler-1.0.0.jar",
          "url": "kuiklySqlite-compiler-1.0.0.jar",
          "size": 63929,
          "sha512": "2c3f93d951db48ece4d40097838cd9f36ee498ad615a18a4d9056a5ac84f4e289430b6b037ad98e72c104185f68d095233525322d39a8647e1aab8bd4a4ffb14",
          "sha256": "bd3ea08fca7b3b66a2944bab8e469aa712ed6c9b795564627d7c249330066602",
          "sha1": "8a8aa40de0c951a9973269fa459681894f01780b",
          "md5": "31bf2f89ad079780a0e545bd47e36c0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.20-1.0.14"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "kuiklySqlite-compiler-1.0.0.jar",
          "url": "kuiklySqlite-compiler-1.0.0.jar",
          "size": 63929,
          "sha512": "2c3f93d951db48ece4d40097838cd9f36ee498ad615a18a4d9056a5ac84f4e289430b6b037ad98e72c104185f68d095233525322d39a8647e1aab8bd4a4ffb14",
          "sha256": "bd3ea08fca7b3b66a2944bab8e469aa712ed6c9b795564627d7c249330066602",
          "sha1": "8a8aa40de0c951a9973269fa459681894f01780b",
          "md5": "31bf2f89ad079780a0e545bd47e36c0b"
        }
      ]
    }
  ]
}
