{
  "formatVersion": "1.1",
  "component": {
    "group": "net.shantu.kuiklySqlite",
    "module": "kuiklySqlite-compiler",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "kuiklySqlite-compiler-1.0.0.jar",
          "url": "kuiklySqlite-compiler-1.0.0.jar",
          "size": 63930,
          "sha512": "c70faadbe607c8ccb9972585a2fb63b143817126eb6182eaedad3657a5d70ffc2565165891f9c3c7cbda5eddd1ceba86063370a0826e2c09123bc80c08e0198c",
          "sha256": "647821dc9a638e829f79de9494504e593f2ca0e3f3d471f35d9d393fc10a9d03",
          "sha1": "1b2b0f55ecfe3c6926dc3b254fbd1ca40371847e",
          "md5": "8c2261ffd9280ea8c91751ae53c466b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.20-1.0.14"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "kuiklySqlite-compiler-1.0.0.jar",
          "url": "kuiklySqlite-compiler-1.0.0.jar",
          "size": 63930,
          "sha512": "c70faadbe607c8ccb9972585a2fb63b143817126eb6182eaedad3657a5d70ffc2565165891f9c3c7cbda5eddd1ceba86063370a0826e2c09123bc80c08e0198c",
          "sha256": "647821dc9a638e829f79de9494504e593f2ca0e3f3d471f35d9d393fc10a9d03",
          "sha1": "1b2b0f55ecfe3c6926dc3b254fbd1ca40371847e",
          "md5": "8c2261ffd9280ea8c91751ae53c466b5"
        }
      ]
    }
  ]
}
